[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 10
dimensions = { columns = 120, lines = 32 }
decorations = "Buttonless"
opacity = 0.88
blur = true
position = { x = 500, y = 200 }
startup_mode = "Fullscreen"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 21.0

[colors]
cursor = { text = "#000000", cursor = "#bebebe" }
