"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = """$directory$character"""
right_format = """$git_branch"""

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'
