require "nvchad.mappings"

local map = vim.keymap.set

map("n", ";", ":", { desc = "CMD enter command mode" })
map("n", "<leader>w", "<cmd>w<cr>", { desc = "Save file" })
map("n", "<leader>q", "<cmd>q<cr>", { desc = "Quit Vim" })
map("n", "й", "y", { desc = "y key" })
map("n", "q", "ц", { desc = "q key" })
map("n", "е", "e", { desc = "e key" })
map("n", "к", "r", { desc = "k key" })
map("n", "е", "t", { desc = "e key" })
map("n", "н", "y", { desc = "n key" })
map("n", "г", "u", { desc = "g key" })
map("n", "ш", "i", { desc = "ш key" })
map("n", "щ", "o", { desc = "щ key" })
map("n", "з", "p", { desc = "з key" })
map("n", "х", "[", { desc = "х key" })
map("n", "ъ", "]", { desc = "ъ key" })
map("n", "ф", "a", { desc = "ф key" })
map("n", "ы", "s", { desc = "ы key" })
map("n", "в", "d", { desc = "в key" })
map("n", "а", "f", { desc = "а key" })
map("n", "п", "g", { desc = "п key" })
map("n", "р", "h", { desc = "р key" })
map("n", "о", "j", { desc = "о key" })
map("n", "л", "k", { desc = "л key" })
map("n", "д", "l", { desc = "д key" })
map("n", "я", "z", { desc = "Я key" })
map("n", "ч", "x", { desc = "Ч key" })
map("n", "с", "c", { desc = "С key" })
map("n", "м", "v", { desc = "М key" })
map("n", "и", "b", { desc = "И key" })
map("n", "т", "n", { desc = "Т key" })
map("n", "ь", "m", { desc = "Ь key" })
map("n", "б", ",", { desc = "Б key" })
map("n", "ю", ".", { desc = "Ю key" })
map("n", "й", "y", { desc = "й key" })
